### ISSUE TITLE
Licence for contribution

### ISSUE THREAD

**Issue by amunizp** [UKHackspaceFoundation/resources#13]
Are we completely bought in on the licence? Why not CC-BY-SA international 4.0?

**Comment by idnorton** [comment]
@amunizp I think you would be better stating your issue with existing and suggesting why you think we should change

**Comment by amunizp** [comment]
OK thanks, hopefully I can express this better. In my humble opinion:
Regarding the licence:  resources/license.md  
Currently it is CC-BY-NC-SA 3.0
My issue is the Non-commercial clause because:
* It makes it incompatible with wikipedia licence
* It makes it incompatible with software licences normally used in hackspaces such as FLOSS (I know it is different, but it muddles things up)
* If say, a member Hackspace would want to bundle it up in a had copy book and sell it in a market fair to benefit their members they could not because of the licence. OK we would have to ask for permission but there is the Grace Hopper motto "It's easier to ask forgiveness than it is to get permission."  
* If the concern is for someone to pinch the whole document and then post it on the big distributors to be sold as an ebook we could swap to G-FDL which has an anti-DRM clause and major distributors currently use DRM.
* It is not a [free culture licence](https://creativecommons.org/share-your-work/public-domain/freeworks/) which I believe goes in line with the general hackspace ethos.

**Comment by syberphunk** [comment]
> It makes it incompatible with wikipedia licence

This isn't wikipedia.

> It makes it incompatible with software licences

This isn't software.

> If say, a member Hackspace would want to bundle it up in a had copy book and sell it in a market fair to benefit their members they could not because of the licence

Having a non commercial license basically says that others can't profit or make monetary gain from other people's work. That's likely the intention (to prevent that happening). I wouldn't want someone getting monetary gain from my work when I would give the work to them freely.

> If the concern is for someone to pinch the whole document and then post it on the big distributors to be sold as an ebook we could swap to G-FDL which has an anti-DRM clause 

That's not the same, though?

> It is not a free culture licence which I believe goes in line with the general hackspace ethos

That allows commercial use, I haven't really seen anything saying that the general hackspace ethos was pro commercial, I've only seen hackspaces ethos be commercial tolerant.

**Comment by idnorton** [comment]
We took this discussion over to the forum https://forum.hackspace.org.uk/t/licence-for-hackspace-foundation-resources/300 and I suspect that's probably a better place to discuss it than an issue.

I'll close this off and people should feel free to re-open it if they disagree
