### ISSUE TITLE
Access Control documentation

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/resources#2]
Working on this in a branch at:

https://github.com/UKHackspaces/resources/blob/hackspace_owners_manual/Hackspace%20Owners%20Manual/Access%20Control/README.md

- [x] Summary

### Access Tokens
- [x] Magnetic swipe
- [x] Contactless overview
- [x] Mifare specifics
- [x] Mifare Application Directory

### Readers
- [ ] Seeed studio RDM880
- [ ] NXP PN532
- [ ] What else?

### Ironmongery
- [x] Fail Open
- [x] Fail Secure
- [x] Abloy EL560
- [x] Cisa locks
- [x] Effeff strikes

### Controllers
- [x] Local caching of data

### Other considerations
- [x] DDA
- [x] Fire escape routes and fire alarms
- [x] Access when the system is down
- [x] Two factor authentication and occupancy sensing

### Access control for tools

* Not sure what we add here at this point but there needs to be mention of it.

### Case Studies
- [ ] London Hackspace
- [ ] Manchester Hackspace
- [ ] Swindon Hackspace

**Comment by idnorton** [comment]
We just had a conversation on telegram about the use of two factor auth outside of normal opening hours to be something you have and something you know.

@notquitehere pointed out that adding PIN to RFID could potentially cause issues for dyslexics and indeed could cause issue for someone with a visual imparement.

@BuildTheRobots then suggested that Leeds have done work to combine this with presence sensing such that the two factor auth only happens when the space is unoccupied which seems like a reasonable potential compromise.

Will write this up in the doc but adding notes here for now.

**Comment by idnorton** [comment]
We're almost done. Needs some more info on readers and we need to get case studies written.

**Comment by amunizp** [comment]
Richmond Makerlabs needs to stop making so many key copies. Might be able to beta test one or two method.

**Comment by amunizp** [comment]
Do any of you have experience in retrofitting something on existing ironmongery? We would like to keep the lock installed. It is just a lever handle.

**Comment by idnorton** [comment]
We moved the Chelmsford discussion over to discourse at https://forum.hackspace.org.uk/t/access-control-to-an-existing-space/63/2

Good point made by @amunizp about access control on tooling, not sure if that belongs here or not but we can probably but some notes about it here and move it later if needed.

**Comment by idnorton** [comment]
Created a new issue #38 for discussion of access control on tooling.

I'd really like to call this done but we're lacking in case studies and advice on readers that people have experience with.

Clearly I need to poke people some more...

@Axford you offered to write some reader stuff and possible case study for Swindon?
@Jonty who's best to poke about getting something from London?
@notquitehere Who's best to poke about getting something from Manchester?

Thank you lovely people :)

**Comment by castaway** [comment]
Swindon Makerspace Access System documented a pile - ready for review/case study including - github.com/swindonmakers/AccessSystem/

**Comment by idnorton** [comment]
k, I'm going to call this done though there are improvements to make the initial document is there and can now be added to without having the initial overhead.
